module Messenger.Render.SpriteSheet exposing
    ( SingleSprite
    , SpriteSheet
    , spriteSheetSize
    )

{-|


# Sprite Sheet

Actually the sprite sheet library should only be used in the Lib.Resource.elm. In the view functions, just use the format "spriteSheetName.spriteName" in normal rendersprite.

See the example in the manual.

@docs SingleSprite
@docs SpriteSheet
@docs spriteSheetSize

-}

import Dict exposing (Dict)


{-| A Single Sprite in a SpriteSheet

The unit of realSize is pixel.

-}
type alias SingleSprite =
    { realStartPoint : ( Float, Float ) -- (x, y)
    , realSize : ( Float, Float ) -- (Width, Height)
    }


{-| SpriteSheet

Users should both name the sprite sheets and every single sprite.
Using it by **format: "sheet\_name.sprite\_name"**

  - Example: renderSprite env.globalData [ imageSmoothing False ] ( 0, 0 ) ( 100,0 ) ("spritesheet1.sp1") will render sp1 from spriteSheet1.
    We recommand to use number suffix to name the separated spritesheet, so different sprite can be handled easily, like "sp1","sp2" can be generated by "sp"++ (String.fromInt no), where no is an Int.

    Sprite sheets are useful when managing the art resourses or making frame-by-frame animations.

-}
type alias SpriteSheet =
    Dict String (List ( String, SingleSprite ))


{-| Get the total number of sprites in a sprite sheet.
-}
spriteSheetSize : SpriteSheet -> Int
spriteSheetSize sheet =
    Dict.foldl (\_ v acc -> acc + List.length v - 1) 0 sheet
